"""initial migration

Revision ID: c9c6aa459986
Revises: 
Create Date: 2024-01-08 21:20:12.891633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c6aa459986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('clientname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('phonenumber',
               existing_type=sa.TEXT(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_contact_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_contact_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_contact_phonenumber'), ['phonenumber'], unique=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_phonenumber'))
        batch_op.drop_index(batch_op.f('ix_contact_name'))
        batch_op.drop_index(batch_op.f('ix_contact_email'))
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=True)
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=128),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(length=64),
               existing_nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('clientname',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.TEXT(length=255), nullable=True))

    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
